# Use the official Python image from the Docker Hub
FROM python:3.11.4

# Set the working directory
WORKDIR /usr/src/app

# Install HDF5 library
RUN apt-get update && apt-get install -y \
    libhdf5-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .


